### ISSUE TITLE
!BUG add/remove collection item

### ISSUE THREAD

**Issue by smile1980** [ninsuo/symfony-collection#100]
Your demo:
https://symfony-collection.fuz.org/symfony3/options/enableButtons

Example: 
1. press remove value "b"
2. press remove value "c"
3. press add value and write "b"
4. press add value and write "c"
5. press submit button
result: left, only two values

form data from request:
form[values][0]:a
form[values][2]:b
form[values][2]:c

index of item collection is the same...

**Comment by ninsuo** [comment]
Hey there, 

Thank you for your report, I think it's a dup of https://github.com/ninsuo/symfony-collection/issues/99

I will have time this weekend to work on it.

Have a good night.
Alain

**Comment by ninsuo** [comment]
Fixed in 00d140b
