### ISSUE TITLE
first index is NaN

### ISSUE THREAD

**Issue by smile1980** [ninsuo/symfony-collection#103]
# jquery.collection.js

var doAdd = function ...

console.log(collection.data('collection-offset')); // undefined
var freeIndex = collection.data('collection-offset') + 1;
console.log(freeIndex); // NaN

#result: <input id="collection_NaN_name">

# init
$('.collection').collection({
     init_with_n_elements: 1
});

**Comment by ninsuo** [comment]
Hello @smile1980 

Thank you for your report, will check this asap.

Alain

**Comment by ninsuo** [comment]
Thank you @smile1980 , issue is now fixed, you can update to 2.1.21.
Have a good day!
