### ISSUE TITLE
init_with_n_elements fills in the front, not the back

### ISSUE THREAD

**Issue by smcjones** [ninsuo/symfony-collection#113]
When using `init_with_n_elements` and not using a minimum value, the properties that are filled in end up at the end, rather than the beginning. This is counter-intuitive.

It would be helpful to have collection-offset default to `elements.length` rather than 0.

```
354             // initializes the collection with a minimal number of elements
355             if (isInitialization) {
356                 collection.data('collection-offset', elements.length);
```

I am happy to submit a PR if this makes sense.

**Comment by ninsuo** [comment]
Hello,

Yes it makes sense, please feel free to throw a PR 👍 

Thanks mate,

Alain

**Comment by smcjones** [comment]
Submitted a PR. 

Thanks!

Sean

**Comment by ninsuo** [comment]
Thank you @smcjones for your contribution, I keep this on my todolist this week-end 👍
