### ISSUE TITLE
Does not work with flex directory structure

### ISSUE THREAD

**Issue by DidierLmn** [ninsuo/symfony-collection#114]
This bundle does not work with the new Symfony flex directory structure, since the ScriptHandler class works with the wrong directories

> *** ninsuo/symfony-collection: Installing Twig form theme...    FAILED: Directory 'app/Resources/views' doesn't exist.
> *** ninsuo/symfony-collection: Installing jQuery plugin...      FAILED: Directory 'web' doesn't exist.

However `app/Resources/views/`, should be `templates/` in flex, and `web/` should be `public/` when using flex

**Comment by gallien-lbr** [comment]
+1 facing the same issue, is there a workaround whilst it is not fixed ?

**Comment by pdhuaman** [comment]
I am using symfony 5 (with flex) and it works like a charm. If you can't install it with composer, just download the bundle manually and copy and paste it to the proper directories.

- ScriptHandler.php --> /vendor/ninsuo/symfony-collection
- jquery.collection.html.twig --> /templates
- jquery.collection.js --> /public/scripts 

Unless I am missing something, and like I say, I have no problem installing this bundle with composer. This bundle supports the flex structure.

**Comment by DidierLmn** [comment]
This issue is more then 2 years old, it is possible it works now 🙂
Also, manually downloading bundles is rarely a good idea 😉

**Comment by pdhuaman** [comment]
Never bothered to check the date. This showed up in my GH inbox as recently opened. Weird though. Maybe a glitch. It should have been closed anyways.
