### ISSUE TITLE
Bad indexes when click Add on ChildForm elements

### ISSUE THREAD

**Issue by Darknessshade** [ninsuo/symfony-collection#117]
Hello,

I have a parent form named "Person" than i can repeat
i have a child form (of Person) named "Booking" than i can repeat

The first Person hierarchy :
aaenbundle_inscriptionALaCarte[person][0][name]
aaenbundle_inscriptionALaCarte[person][0][firstname]
aaenbundle_inscriptionALaCarte[person][0][booking][0][date]

It's all right. But the second child form (Booking) hierarchy has a problem : 
aaenbundle_inscriptionALaCarte[person][1][booking][1][date]

I'm still in the first Person hierarchy, and the result has to be like this : 
aaenbundle_inscriptionALaCarte[person][0][booking][1][date]

I'm doing somthing wrong or it's a bug ?
The problem is that the data is not saved correctly, 
and the form create 2 persons with 2booking,
instead of 1 person with 2 booking.

Thank you for your help.
Cédric

**Comment by janrop** [comment]
Experiencing the same issue. 
Nesting via the 'children' option only seems to work one level deep. 
After that the error you describe occurs.

**Comment by Darknessshade** [comment]
Hello janrop,

finaly i developed my own collection library in typescript. There are not the sames possibility, but it respond to my needs.
