### ISSUE TITLE
Not compatible with PHP 7.1 ?

### ISSUE THREAD

**Issue by benbet** [ninsuo/symfony-collection#120]
Hello,

I have an error when I want to install symfony-collection in my project.

 Problem 1
    - This package requires php >=5.3.9,<=7.0.22 but your PHP version (7.1.0) does not satisfy that requirement.

It's not possible to use symfony-collection with PHP 7.1 ??

Regards
Ben

**Comment by ninsuo** [comment]
Hi Ben,

This plugin has no special requirement (you can check the composer.json)
You should have an issue with another dependency of your project.

Have a great day,
Alain
