### ISSUE TITLE
Controls breaks in newline

### ISSUE THREAD

**Issue by chapterjason** [ninsuo/symfony-collection#126]
I'm not sure where this issue comes from, but the controls after the input breaks in a newline.

![screenshot from 2018-04-28 12 07 54](https://user-images.githubusercontent.com/1337562/39395275-fc8bd1d0-4adc-11e8-9fce-bd91143f9820.png)
![image](https://user-images.githubusercontent.com/1337562/39395298-43df21e0-4add-11e8-845f-cd1317a49946.png)

But after adding class `input-group` and `input-group-append` it's working.

![image](https://user-images.githubusercontent.com/1337562/39395293-214137cc-4add-11e8-9f9e-6c931ce25273.png)
![image](https://user-images.githubusercontent.com/1337562/39395305-5d6f7056-4add-11e8-9c64-d1ef58b4ab76.png)

**Comment by ninsuo** [comment]
Hello !

Thanks for your message and sorry for the delay.

You need to overwrite your form theme in order to add those classes. Please read the Symfony documentation, at http://symfony.com/doc/current/form/form_customization.html

Have a great day,
Alain
