### ISSUE TITLE
Deleting with order_by

### ISSUE THREAD

**Issue by Punt13140** [ninsuo/symfony-collection#133]
Hi,

I'm having an issue...

I have an entity Application
```

/**
class Application implements NotifyPropertyChanged
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;


    /**
     * @var \MyBundle\Entity\ApplicationResponsables
     *
     * @ORM\OneToMany(targetEntity="MyBundle\Entity\ApplicationResponsables", mappedBy="application",orphanRemoval=true, cascade={"persist", "remove"})
     * @ORM\OrderBy({ "type" = "DESC"})
     */
    private $responsables;


```

ApplicationResponsables entity : 
```

class ApplicationResponsables
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \MyBundle\Entity\Application
     *
     * @ORM\ManyToOne(targetEntity="MyBundle\Entity\Application", inversedBy="responsables")
     */
    private $application;

    /**
     * @var \MyBundle\Entity\Responsable
     *
     * @ORM\ManyToOne(targetEntity="MyBundle\Entity\Responsable", inversedBy="resp_applis", cascade={"persist"})
     */
    private $responsable;


    /**
     * @var \MyBundle\Entity\TypeResponsable
     *
     * @ORM\ManyToOne(targetEntity="MyBundle\Entity\TypeResponsable", inversedBy="appli_resp")
     */
    private $type;

```

And Responsable entity has a unique fields : 
```

class Responsable
{



    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="Uid", type="string", unique=true)
     */
    private $uid;
```

my js :
 ```

           $('.collection-responsable').collection({
                prefix: 'collection-responsable',
                add: '<br><a class="btn btn-primary" href="#"><span class="glyphicon glyphicon-plus"></span> Ajouter un responsable</a>',
                remove: '<a class="btn btn-danger" href="#"><span class="glyphicon glyphicon-remove"></span></a>',
                allow_up: false,
                allow_down: false,
                allow_duplicate: false,
                add_at_the_end: true
            });
```

But when I edit an Application, and I delete an ApplicationResponsable,
i have an error 
`updateAction Appli : An exception occurred while executing 'UPDATE responsable SET Uid = ? WHERE id = ?' with params ["coucou", 68]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'coucou' for key 'UNIQ_52520D076BD640E6' `

If i delete the 

`
     * @ORM\OrderBy({ "type" = "DESC"})
`
in Application entity, everything is working ?
Is this coming from your bundle or am I doing something wrong in Symfony (2.7) ?

**Comment by ninsuo** [comment]
Hey there!

For Doctrine, it is easier to use a position field: 
https://symfony-collection.fuz.org/symfony3/basic/positionField

With a position column, IDs of your entity collection will not be changed dynamically, and thus your relations will not be broken.

Have a great day,
Alain

**Comment by Punt13140** [comment]
Mmmh..
But I don't want to change the position, I just want that when I edit my Application, 
my ApplicationResponsables are ordered by my field $type.

Adding a position field will do the job ?

**Comment by ninsuo** [comment]
Yes.

In fact, when you delete a collection row in the "default" way, form is reconstructed and this may break your doctrine mapping.

Using the position method is safer in that case. You don't even need to persist the position field, the idea is just to not reconstruct the form when adding/removing an element.

Cheers

**Comment by Punt13140** [comment]
True!

Thanks man ! Realised I had already read the link you gave me...
But I didn't understand it was related to my problem.

Thanks again !
Closed.

**Comment by ninsuo** [comment]
Superb.
Maybe I can improve the doc to clarify it?
Any suggestions are welcome because I'm totally in the grindstone!
Cheers!
A
