### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by grekpg** [ninsuo/symfony-collection#148]
Directory '.../vendor/../app/Resources/views' doesn't exist.

**Comment by duncan-qabana** [comment]
If you require the lastest version or dev-master, you can see on [this line](https://github.com/ninsuo/symfony-collection/blob/88db2caea7bba13cd7a7beb938fa706a340b38e9/ScriptHandler.php#L56) that it searches both directories. You can ignore the error when installing
