### ISSUE TITLE
Unexpected character "&" in app\Resources\views\jquery.collection.html.twig at line 755.

### ISSUE THREAD

**Issue by monsefoster** [ninsuo/symfony-collection#24]
Hello. I followed the steps for installation but I keep getting this error. 

How can I fix this?

**Comment by ninsuo** [comment]
Hello,

Can you please give me more details?

The jquery.collection.html.twig file is only 34 lines, so this error may be related to the way you're using it more than itself.

**Comment by monsefoster** [comment]
Hey. I don't know what happened but I apparently I downloaded the wrong file. Downloaded it again and it works fine. Thank you very much.
