### ISSUE TITLE
Hide __#label__ label

### ISSUE THREAD

**Issue by monsefoster** [ninsuo/symfony-collection#28]
Hello Guys, I'm using the plugin and was wondering if there's a way to hide the __0label__, __1label__ for the collections? It looks weird and I have no idea how to customize it. 

![image](https://cloud.githubusercontent.com/assets/1691228/14541336/4ce42f44-0253-11e6-85ef-338495f20f63.png)

Thanks.

**Comment by Aigzy** [comment]
Same problem here, can't find a solution. Maybe a changement in the last Symfony version unsupported by the plugin

**Comment by ninsuo** [comment]
Thanks for the report mates. 
Can you please tell me which Symfony version you're using?

**Comment by Aigzy** [comment]
2.8.* version for me

**Comment by ninsuo** [comment]
I think you are dumping your collection field using `{{ form_row() }}` which is the compilation of `{{ form_label() }}`, `{{ form_widget() }}` and `{{ form_errors() }}`. 

You should use `{{ form_widget() }}` and `{{ form_errors() }}` instead.

If not, please provide the way your form collection is dumped in your view.

**Comment by ninsuo** [comment]
I developed a demo available at http://symfony-collection.fuz.org/troubleshoot/hide-form-labels
There are some broken links at the top, but don't worry I'm going to fix #18 within some minutes.

**Comment by monsefoster** [comment]
I think I'm doing it wrong because they're still there.

```
{% form_theme form '::jquery.collection.html.twig' %}
 <div class="row">
                                    {{ form_label (form.rejections)}}
                                    {{ form_errors(form.rejections)}}
                                    {{ form_widget(form.rejections, {'attr': {'class': 'my-selector'} }) }}
                                </div>

 <script type="text/javascript">
                            $('.my-selector').collection();
                        </script>
```

ReviewType.php
`... 
$builder
                ->add('rejections', 'collection', array(
                    'label' => 'Add Rejections (if applies):',
                    'type' => new ReportRejectionReasonType(),
                    'allow_add' => true,
                    'allow_delete' => true,
                    'prototype' => true,
                    'attr' => array(
                        'class' => 'my-selector',
            )));`

ReportRejectionReasonType.php
```
$builder
                ->add('reason', null, array(
                    'label' => '(*) Rejection Reason: ',
                    'attr' => array(
                        'class' => 'form-group',
                    )
                ))
                ->add('comments', null, array(
                    'label' => 'Comments: ',
                    'attr' => array(
                        'class' => 'form-group',
                    )
                ))
        ;
```

**Comment by ninsuo** [comment]
Just remove `{{ form_label (form.rejections)}}` ?

**Comment by monsefoster** [comment]
I did, and this is what happens:

With  {{ form_label (form.rejections)}}
![before](https://cloud.githubusercontent.com/assets/1691228/16390454/dca760ae-3c70-11e6-8605-ae5239cf33c8.PNG)
Without  {{ form_label (form.rejections)}}
![after](https://cloud.githubusercontent.com/assets/1691228/16390458/e31e823c-3c70-11e6-98d9-31fbaaf13eac.PNG)

**Comment by ninsuo** [comment]
Can you please fork the demo website and reproduce the issue on it?
That's easier to help if i have a running form having the issue.

**Comment by iSDP** [comment]
This issue still persists.
Normally, `__name__` gets replaced for the index number, this happens properly.
What doesn't happen is that `__name__label__` doesn't get replaced properly, only the first part, causing the `#label__` issue.

Could you rework it so it replaces `__name__label__` with the right value?

**Comment by iSDP** [comment]
```
'entry_options' => array(
    'label' => false,
    // ...
),
```
is a temporary fix on your CollectionItem's options.

**Comment by RELAXccc** [comment]
Was this fixed? Or am I still doing sth. wrong?
