### ISSUE TITLE
Ids getting changed after removal of an Element

### ISSUE THREAD

**Issue by turkelt0n** [ninsuo/symfony-collection#31]
When i'm deleting an item from a collection, the id's of the remaining items of that collection are getting decreased.

Example:

[A] => &lt;div id="1">
[B] => &lt;div id="2">
[C] => &lt;div id="3">

After deleting Item [B]

[A] => &lt;div id="1">
[C] => &lt;div id="2"> (not "3")

Is this the expected behaviour? If so, is there a easy way to tweak the plugin keep the ids as they are?

**Comment by BoShurik** [comment]
See https://github.com/ninsuo/symfony-collection/issues/20
Maybe workaround is here: https://github.com/ninsuo/symfony-collection/pull/22 but not merged yet
