### ISSUE TITLE
Rely on existing button instead of generating one

### ISSUE THREAD

**Issue by Soullivaneuh** [ninsuo/symfony-collection#33]
On this [sample](http://symfony-collection.fuz.org/options/customButtons), it says you can use custom button thanks to this:

```javascript
$('.form-collection').collection({
    up: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-arrow-up"></span></a>',
    down: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-arrow-down"></span></a>',
    add: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span></a>',
    remove: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-trash"></span></a>'
});
```

But for my case, I want to add the remove button as an input group addon: http://getbootstrap.com/components/#input-groups-buttons

Is that possible to tell you lib to rely on an existing button (generated from my form theme) instead of a generated one?

**Comment by ninsuo** [comment]
You can of course, please look at the following example:

http://symfony-collection.fuz.org/advanced/customFormTheme

Enjoy

**Comment by Soullivaneuh** [comment]
This exactly what I want! Thanks! :+1:
