### ISSUE TITLE
Table view render

### ISSUE THREAD

**Issue by Quovandius** [ninsuo/symfony-collection#36]
Hi,

I have found this plugin today, and its amazing =) Very thanks for this, collection form is very hard to manage for me.

One suggestion (i don't know if you have time for this) : a table view ?
Label on thead, one row per entity, one column per field and last column with button ?

I have made some tests on symfony form render, and all of these are fail :s

once again, thanks for this =)

**Comment by razbounak** [comment]
I have the same problem
When I copy paste the form theme of the exemple, it's works
But when I replace a "div" by a "tr", nothing works

Thanks for your help

**Comment by ninsuo** [comment]
Possible using the `elements_selector` option and having strong skills in form theming.

Demo available at https://symfony-collection.fuz.org/symfony3/basic/inATable
