### ISSUE TITLE
allow_remove not an existing option

### ISSUE THREAD

**Issue by turkelt0n** [ninsuo/symfony-collection#38]
According to the "Basic Usage"-Segment  (https://github.com/ninsuo/symfony-collection#basic-usage)
there is a 'allow_remove'-option within the Collection-Type. Well, there isn't :-)

I might be mistaking, but i think this has something to do with the 2.0.0 Upgrade.

**Comment by ninsuo** [comment]
Hi

Still enjoying my summer hollidays, will come back full of power very soon

A

**Comment by turkelt0n** [comment]
Keep Enjoying ;) I did some trivial mistake.

**Comment by moroine** [comment]
Hi, 

I add the same error :/ 

May I made the same mistake :/

**Comment by ninsuo** [comment]
Hello @moroine,

Can you please send more details?

This option exists [here](https://github.com/ninsuo/symfony-collection/blob/master/jquery.collection.js#L50), you can try it live [here](http://symfony-collection.fuz.org/options/enableButtons) and see examples.

Thanks,
