### ISSUE TITLE
Incompatibility with jQuery3

### ISSUE THREAD

**Issue by raphaelvigee** [ninsuo/symfony-collection#39]
I'm using this plugin with the `single_add_button` enabled, and every time I click on it, I got : 

```
Uncaught TypeError: element.find(...).andSelf is not a function

(anonymous function)	@	fd6bf6b.js:2951
each					@	fd6bf6b.js:2
each					@	fd6bf6b.js:2
dumpCollectionActions	@	fd6bf6b.js:2948
(anonymous function)	@	fd6bf6b.js:3284
each					@	fd6bf6b.js:2
each					@	fd6bf6b.js:2
$.fn.collection			@	fd6bf6b.js:3140
(anonymous function)	@	fffl:20

```

The only I found to "fix" this issue is to downgrade to jQuery2.

**Comment by elterpro** [comment]
You could just replace the "andSelf()" with "addBack()" as seen here https://api.jquery.com/andself/ instead of using an older version of jQuery, because the function is also deprecated.

**Comment by raphaelvigee** [comment]
A PR could be a good thing ;)

Is @ninsuo still alive ? :3

**Comment by ninsuo** [comment]
Hello,

Oh yeah I am, sorry for being silent so long but I was on summer vacations and there are no way I bring a computer with me when I'm out :) 

There are many issues open, I'll try to answer them this week.

Thanks!
A

**Comment by raphaelvigee** [comment]
Oh great :) I thought this package was slowly dying...

**Comment by ninsuo** [comment]
will have a look today :)

**Comment by ninsuo** [comment]
Done, and with a new page to test other jquery versions.
http://symfony-collection.fuz.org/troubleshoot/custom-jquery-version

Thanks for your report!
