### ISSUE TITLE
Set position by using drag and drop

### ISSUE THREAD

**Issue by hason** [ninsuo/symfony-collection#4]

**Comment by ninsuo** [comment]
:+1:

**Comment by shadypierre** [comment]
:+1:

**Comment by ninsuo** [comment]
Sorry for the delay, #15 finally adds drag & drop support.

**Comment by ninsuo** [comment]
Release created ( 1.2.0 )
Live demo here: http://symfony-collection.fuz.org/options/dragAndDrop
Please let me know if you notice something that looks wrong.
