### ISSUE TITLE
Place manually "add-button" in the page

### ISSUE THREAD

**Issue by flavienaudin** [ninsuo/symfony-collection#40]
Hi,
I would to know if is it possible to place manually the 'add-button" of a collection in the page where the form is displayed ?
To illustrate my question, here my situation ; I had a form with 2 independent collections. I would like to group both add-buttons in a button-group (like a toolbar)  instead of displayed them each above its collection.

I tried to add 2 add-buttons with "_collection-prefix_-add" class and specify the option "prefix" on the JS options, but it doesn't work. 

First I think I wrongly use the "collection-prefix" as each button normally added by the plugin has "collection-class" without taking into account my "prefix" option.
Secondly, each button should have a way to specify the collection which it applies to.

Thank you for your answer.

Flavien

**Comment by flavienaudin** [comment]
Hi,
Is there an answer to my question ? Perharps it's not clear enough ?
Thanks
Flavien

**Comment by ninsuo** [comment]
Hello Flavian,

No that's clear, I'll try to answer tonight or tomorrow morning.

Thanks for your patience i'm quite busy those days 😓

Alain

**Comment by ninsuo** [comment]
This is not possible as is, and it will take me something like an hour to implement. 
I'll work on it today.
Thanks

**Comment by flavienaudin** [comment]
Hi, Is there any new about this issue ?
Thanks

**Comment by flavienaudin** [comment]
Thank you very much for your work. 
I hope it will also be helpful for others.
