### ISSUE TITLE
Override block on child collection 

### ISSUE THREAD

**Issue by everio** [ninsuo/symfony-collection#43]
Hi,
Any solution to override child collection block ?

Example : 
product entity has collection of article entity
and article entity has collection of price entity

First widget works :
`{% block _product_articles_entry_widget %}`

But how to do for prices ?
`{% block _product_articles_prices_entry_widget %}`  don't work.

Here the javascript :

```
`$('.article-collection').collection({
        parent: 'article',
        after_add: function(collection, element) {
          handleNewDomElements();
        },
        allow_up: false,
        allow_down: false,
        children: [{
             selector: '.prices-collection',
             prefix: 'price',
         }]
      });`
```

**Comment by mktcode** [comment]
Although this is a good question, it is not really related to this plugin but to symfony form rendering.

**Comment by marcel-burkhard** [comment]
try `_product_articles_entry_prices_entry_widget`
