### ISSUE TITLE
Uncaught TypeError: element.children(...).andSelf is not a function(…) in jquery.collection.js:289

### ISSUE THREAD

**Issue by martin-anacabe** [ninsuo/symfony-collection#46]
The problem is that in this line the *andSelf* deprecated method is called instead of the *addBack* method. Making this change, the problem is solved.

Change:

```javascript
var actions = element.children().andSelf().filter('.' + settings.prefix + '-actions');
```

```javascript
var actions = element.children().addBack().filter('.' + settings.prefix + '-actions');
```

**Comment by martin-anacabe** [comment]
This problem is solved. But in npm, the last release is the version V1.1.3. Please, update this package in npm

**Comment by ninsuo** [comment]
Oh yep, thanks

**Comment by martin-anacabe** [comment]
You are welcome, amazing work!
Congratulations and keep moving!
