### ISSUE TITLE
It would be great to pre-display a number of items

### ISSUE THREAD

**Issue by leroy0211** [ninsuo/symfony-collection#5]
For example to display 3 empty values on page load:

```
$('#element').collection({
     display_default: 3
});
```

**Comment by ninsuo** [comment]
Yes this would work only for a minimal number of items, but I get your point.
Thanks for the feedback, will think about it :-).

**Comment by 84pixels** [comment]
They have solution for add X row(s) by default ?

![capture d ecran 2015-07-20 a 17 41 42](https://cloud.githubusercontent.com/assets/5638656/8780026/be786a9c-2f06-11e5-9c3b-a1c0e270d8a9.png)

Can you help me please ?

**Comment by ninsuo** [comment]
Not yet. Will have a look tonight.

**Comment by ninsuo** [comment]
Thank you for your suggestions @leroy0211  and @84pixels .
This also fixes the issue where the collection is initialized with fewer items than the `min` option.

You can use the following option to do what you expect:

```js
        $('.form-collection').collection({
            init_with_n_elements: 5
        });
```

You can try it live at:
http://symfony-collection.fuz.org/options/givenMinimumElements

Bower will be updated soon.

**Comment by 84pixels** [comment]
Thanks a lot!
