### ISSUE TITLE
hide_useless_buttons set to false permanently hides add buttons when at max

### ISSUE THREAD

**Issue by jeffhinshaw** [ninsuo/symfony-collection#51]
Using the following configuration, all add buttons permanently disappear upon hitting the max number of elements, even after deleting elements.

```javascript
$('.collection').collection({
    hide_useless_buttons: false,
    min: 1,
    max: 4
});
```

It appears `dumpCollectionActions` will first set the add button's display to 'none' or '' only if hide_useless_buttons is set to false, but then sets the display of all add buttons to 'none' if the max number of elements is hit regardless of the hide_useless_buttons setting.

I've replicated this on the [demo site](http://symfony-collection.fuz.org/symfony3/options/hideMoveUpDown) as well upon hitting the default 100 element max.

**Comment by ninsuo** [comment]
👍

**Comment by jeffhinshaw** [comment]
Thanks for the quick response!

It looks like now if you use the following configuration, it inadvertently keeps showing the "rescue add" button upon hitting the max number of elements.

```javascript
$('.collection').collection({
    hide_useless_buttons: false,
    add_at_the_end: true,
    max: 4
});
```

**Comment by ninsuo** [comment]
Hi,

This is how it looks on my screen, I see nothing buggy here.

You can still see the rescue button because you explicitly disabled "hide useless buttons" (which mean, keep showing buttons even if they don't work anymore).

Thanks,

![screen shot 2017-02-06 at 23 12 13](https://cloud.githubusercontent.com/assets/4152132/22668649/be383fe2-ecc1-11e6-9827-08434f63ae50.png)

**Comment by jeffhinshaw** [comment]
That makes sense. Perhaps then the ".*-action-disabled" class could be added to the button in this situation.

**Comment by ninsuo** [comment]
Sure.
Can you create a new issue for this?
Cheers,
