### ISSUE TITLE
Unclear documentation on composer

### ISSUE THREAD

**Issue by timothymctim** [ninsuo/symfony-collection#58]
I'm not sure why/how this (great) component is installable using `composer`.

The way I've configured it now, is just by adding a symlink to the `symfony-collection/jquery.collection.html.twig` file in my `vendor` directory.
What I would actually expect is that I wouldn't have to symlink myself and that the default Symfony directory structure is used so that I would be able to use `{% form_theme myForm 'AppBundle::jquery.collection.html.twig' %}` directly ‘out of the box.’

It might also be an idea to use `robloach/component-installer` ([github](https://github.com/RobLoach/component-installer)) to install `jQuery` as well so that the plugin is self-contained.

**Comment by timothymctim** [comment]
After having a look at robloach's `component` and how to turn the repository into a bundle, it seems a bit like a configuration overkill to me. So I guess the current solution of just creating some syslinks yourself is the best solution. However, it would be great to add a single sentence to the documentation, clarifying that one need to symlink/hardlink/copy the file themselves.

**Comment by rapemer** [comment]
I think there can be simple Composer ScriptHandler that will execute hard-copy or symlink of JavaScript automatically to the folder "Resources/public/js/" and simple CompilerPass that will insert form_theme inside container parameter "twig.form.resources" (that holds form themes information).

If you want, I can create PR...

**Comment by ninsuo** [comment]
Will look at this tonight.

**Comment by ninsuo** [comment]
Done. I didn't create tags yet because I need to write the doc, but you'll soon be able to use:

```json
    "scripts": {
        "post-install-cmd": [
            ...
            "Fuz\\Symfony\\Collection\\ScriptHandler::postInstall"
        ],
        "post-update-cmd": [
            ...
            "Fuz\\Symfony\\Collection\\ScriptHandler::postUpdate"
        ]
    },
```

**Comment by ninsuo** [comment]
I updated the demo website and this is far, far more comfortable to use this.
This brings a high value to the project, thanks for your feedback!
Cheers.
