### ISSUE TITLE
Installation on Symfony 3.3: is there a manual action to perform?

### ISSUE THREAD

**Issue by BenoitDuffez** [ninsuo/symfony-collection#61]
I am new to Symfony. I have 3.3 and I have installed your package with:

    composer require ninsuo/symfony-collection

Then (I don't know if that was necessary because I'm new to composer too):

    composer install

Then I added the code to my form type (add the required parameters) and edited my form as per the readme on this project (my bundle is `AppBundle`):

     {% form_theme myForm 'AppBundle::jquery.collection.html.twig' %}

Then Symfony fails to load it:

    Unable to find template "::jquery.collection.html.twig" (looked into: /home/xxx/projects/qiv/app/Resources/views, /home/xxx/projects/qiv/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form).

So my question is: should composer/symfony automatically do their magic to find that template, or do I need to copy the Twig template (and the javascript file) to my app resources directory so that Symfony finds it?

**Comment by ninsuo** [comment]
Hello,

This question is related to #58 
I will have a look to it at the beginning of next week.

Until that time, yes, you'd better copy the Twig template somewhere manually.

Thanks for your patience,

**Comment by BenoitDuffez** [comment]
OK I have read carefully #58 and forgot to mention that in my question.

So first of all thanks for the insanely fast feedback, and then I'll copy the files manually for the time being.

Cheers
