### ISSUE TITLE
Use init_with_n_elements parameter doesn't work

### ISSUE THREAD

**Issue by Darknessshade** [ninsuo/symfony-collection#62]
Hello,

Uncaught TypeError: Cannot read property 'attributes' of undefined line 180 when you use init_with_n_elements

```javascript
                    var jqNode = $(node);
                    $.each(node.attributes, function (i, attrib) {
                        if ($.type(attrib.value) === 'string') {
                            jqNode.attr(attrib.name.replace(toReplace, replaceWith), attrib.value.replace(toReplace, replaceWith));
                        }
                    });
                    $.each(jqNode.data(), function (name, value) {
                        if ($.type(value) === 'string') {
                            jqNode.data(name.replace(toReplace, replaceWith), value.replace(toReplace, replaceWith));
                        }
                    });
```

**Comment by ninsuo** [comment]
I keep it open as it looks to have issues anyway.
http://symfony-collection.fuz.org/symfony3/options/givenMinimumElements

**Comment by Darknessshade** [comment]
Here we go !
Miss a 's' to element[0] -> elements[0]

```javascript
#Line 192
var element = elements.eq(index);
    replaceAttrDataNode(element[0]);
    element.find('*').each(function () {
        replaceAttrDataNode(this);
});
```

TO

```javascript
#Line 192
var element = elements.eq(index);
    replaceAttrDataNode(elements[0]);
    element.find('*').each(function () {
        replaceAttrDataNode(this);
});
```

**Comment by ninsuo** [comment]
Which jQuery version are you using?
I'm asking because I can't reproduce this in 2.1.1 (and applying your fix breaks).
Thanks!

**Comment by ninsuo** [comment]
Strange thing: works with 3.2.1, it may explain why it works for you when you set the jquery element instead of the node directly.

After investigating, it looks like element[0] crashes when elements.eq(index) returns an empty array. And it does because of line 330:

```
                    var index = elements.length + 1;
```

The "virtually clicked" position of the add button should be the last element, so `var index = elements.length - 1`.

Fix incoming.

**Comment by Darknessshade** [comment]
Hello, i have jquery-2.1.4, i go to update it...
Thank you.

**Comment by ninsuo** [comment]
No worries, I fixed the issue on my side, you don't need to update jquery.
A
