### ISSUE TITLE
Can't find collection: undefined

### ISSUE THREAD

**Issue by BenoitDuffez** [ninsuo/symfony-collection#64]
I may have done something wrong but I can't figure out what.

First, the template doesn't seem to be working. I'm using bootstrap and a self template so here's what I have:

    {% form_theme form
        'bootstrap_3_layout.html.twig'
        'form/jquery.collection.html.twig'
        _self
    %}

With that only, I have the following errors:

    jquery.collection.js: the prefix used in descendant field names is mandatory, you can set it using 2 ways:
    jquery.collection.js:645 jquery.collection.js: - use the form theme given with this plugin source
    jquery.collection.js:646 jquery.collection.js: - set name_prefix option to  '{{ formView.myCollectionField.vars.full_name }}'

But I got that away by applying the `name_prefix` manually.

What bothers me is that when I click on the + button, I have that:

    Uncaught Can't find collection: undefined (anonymous) @ jquery.collection.js:710

I have read a little bit the code, from what I understand it's trying to jump from the `a` tag (+ button) to the matching collection, in order to retrieve its settings. The problem is that it can't find the collection.

Here's my form:

	$builder
		->add('sections', CollectionType::class, [
			'entry_type' => SectionType::class,
			'allow_add' => true,
			'allow_delete' => true,
			'prototype' => true,
			'attr' => array(
				'class' => 'sections'
			),
			'by_reference' => false,
		]);

Here's how my sections are printed:

    <h3>Sections</h3>
    <div class="sections" data-prototype="{{ form_widget(form.sections.vars.prototype)|e('html_attr') }}">
        {{ form_widget(form.sections) }}
    </div>

Here's the section template:

    {% block _appbundle_quote_sections_entry_widget %}
        <div class="row">
            <div class="col-md-8">
                {{ form_row(form.title) }}
            </div>
            <div class="col-md-4">
                {{ form_row(form.rate) }}
            </div>
        </div>
    {% endblock %}

So as you can see my collection is wrapped in a div which class is `sections`.

Here's where your plugin is invoked:

    <script type="text/javascript">
        $('.sections').collection({
            prototype_name: '{{ form.sections.vars.prototype.vars.name }}',
            allow_add: true,
            allow_remove: true,
            name_prefix: '{{ form.sections.vars.full_name }}',
            fade_in: true,
            fade_out: true,
            drag_drop: true
        });
    </script>

So why is the + button created without the proper link back to the collection?
FYI at line 710 (when throwing), the `data('collection')` equals to `undefined`.

Also, when inspecting the + button, I found out that there is a `collectionElement` data item (that's the only data in the button) that contains the link to the collection.

So in the browser console, this finds the collection of the first + button in the page:

    $("#"+$($('.collection-add')[0]).data('collectionElement')).parent()

This patch actually makes it work:

    --- a/web/js/jquery.collection.js
    +++ b/web/js/jquery.collection.js
    @@ -707,7 +707,11 @@
                             var collection = $('#' + that.data('collection')).find('.' + that.data('collection') + '-collection');
                             var settings = collection.data('collection-settings');
                             if (undefined === settings) {
    -                            throw "Can't find collection: " + that.data('collection');
    +                            var collection = $('#' + that.data('collectionElement')).parent();
    +                            var settings = collection.data('collection-settings');
    +                            if (undefined === settings) {
    +                                throw "Can't find collection: " + that.data('collection');
    +                            }
                             }
                         }

Do you want to fix this issue like that, or maybe I did something wrong? Do you want a PR?

**Comment by BenoitDuffez** [comment]
Note that this patch is not a solution but a hack in fact.

Indeed, this only works if there is at least one item (otherwise `collectionElement` doesn't exist).

**Comment by ninsuo** [comment]
I will have time to code next week, I'll have a close look to this.
Thanks!

**Comment by BenoitDuffez** [comment]
I think I got it.

You're trying to retrieve the collection when a button is clicked (`that`):

    var collection = $('#' + that.data('collection'));

So I just need to define the collection ID as a data attribute and I'm good!  
So, I replaced my collection div to add an ID:

    <div class="sectionscoll" id="sections"> ... </div>

Then in the collection settings, add the reference in the links:

    $('.sectionscoll').collection({
    ...
        up: '<a href="#" class="btn btn-default" data-collection="sections"><span class="glyphicon glyphicon-arrow-up"></span> Move section up</a>',
        down: '<a href="#" class="btn btn-default" data-collection="sections"><span class="glyphicon glyphicon-arrow-down"></span> Move section down</a>',
        add: '<a href="#" class="btn btn-default" data-collection="sections"><span class="glyphicon glyphicon-plus-sign"></span> Add section</a>',
        remove: '<a href="#" class="btn btn-default" data-collection="sections"><span class="glyphicon glyphicon-trash"></span> Remove section</a>',
    ...

So now the button is able to retrieve a link to the collection and everything works.

I'm not sure this is how it's intended (I'm rather new to Symfony and javascript) but it works!

**Comment by BenoitDuffez** [comment]
Another comment just for clarity.

I got it to work. I had a hard time doing so because I'm using collections of collections and self form templates (which didn't set any ID for individual 1st level collections).

So now everything is working as expected so I'm closing the issue. This was not a bug but a configuration issue.
Feel free to reopen and/or comment if you think my issue was worth documenting/changing the code for.
