### ISSUE TITLE
Add button being invisible when you aim max element. But when you remove an element, Add button don't appear

### ISSUE THREAD

**Issue by Darknessshade** [ninsuo/symfony-collection#65]
Hello
When you set max value and your collection aim max element, the add button disapear = Normal
But when you remove an element, the add button don't appear.

```javascript
#Line 524 after toDelete.remove();
if( elements.length <= settings.max ){
    dumpCollectionActions(collection, settings, false);
    }
```

**Comment by ninsuo** [comment]
Thank you, this is easily reproductible on the demo website:
http://symfony-collection.fuz.org/symfony3/options/numberCollectionElements

Looks like buttons appear again once you removed 2 elements though.
Investigating.

**Comment by ninsuo** [comment]
Ok this is an issue following the new `settings.fade_out` option now enabled by default.

fade_out let deleted elements be removed nicely (using fadeOut animation), but this has the side effect that when we're in this part of the code, element is still not yet deleted (compared to before).

Fix incoming within minutes.

**Comment by ninsuo** [comment]
Fixed your issue, you can test behavior directly on:
http://symfony-collection.fuz.org/symfony3/options/numberCollectionElements

Still have issues: when removing the last element with min > 0, we still can see trashes
Will fix this tomorrow (and plan to QUnit this because that's a pain to maintain ^^)

**Comment by Darknessshade** [comment]
Hello, thank you for your reactivity !

**Comment by ninsuo** [comment]
fixed
