### ISSUE TITLE
Added items appears at the top

### ISSUE THREAD

**Issue by BenoitDuffez** [ninsuo/symfony-collection#66]
I don't know if it's my configuration or if it is the intended behavior, but when I add a new item (be it in the main collection or in the children collection), it appears at the top.

    $('.sections').collection({
        prototype_name: '{{ form.sections.vars.prototype.vars.name }}',
        name_prefix: '{{ form.sections.vars.full_name }}',
        allow_add: true,
        allow_remove: true,
        add_at_the_end: true,
        fade_in: true,
        fade_out: true,
        prefix: 'sections',
        init_with_n_elements: 1,
        up: '',
        down: '',
        add: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span> Add section</a>',
        remove: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-trash"></span> Remove section</a>',
        position_field_selector: '.section-position',
        drag_drop: true,
        children: [{
            selector: '.items',
            prototype_name: '{{  form.sections.vars.prototype.items.vars.prototype.vars.name }}',
            name_prefix: '{{ form.sections.vars.prototype.items.vars.full_name }}',
            init_with_n_elements: 1,
            fade_in: true,
            fade_out: true,
            up: '',
            down: '',
            add: '<a href="#" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus-sign"> Add new item in this section</span></a>',
            remove: '<a href="#" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-trash"></span></a>',
            position_field_selector: '.item-position',
            add_at_the_end: true,
            prefix: 'items'
        }]
    });

I would like the new items to be created at the last position. Is there a setting flag or something to change?

**Comment by jeffhinshaw** [comment]
I have encountered the same issue. It appears to be a bug with the latest release. This only happens when the "add_at_the_end" option is set to true. Setting this option to false will make the addition of items act as expected.

**Comment by BenoitDuffez** [comment]
OK thanks for the heads up. I'd rather have just one button for now. I'll wait or try to fix it and submit a PR.

**Comment by ninsuo** [comment]
Hi there, it might indeed be related with the init_with_n_elements issue.
I'm releasing a fixed version tonight, please don't hesitate to reopen your issue if you still have troubles.

**Comment by BenoitDuffez** [comment]
That does not fix the issue, the items still appear at the top

**Comment by ninsuo** [comment]
Ok thanks, there's another issue with add_at_the_end.

**Comment by ninsuo** [comment]
Should be good, please try again and let me know if you have any issue.

**Comment by BenoitDuffez** [comment]
Great job! Thank you so much for the quick feedback.

Also, now that I have fully integrated your plugin into my product, huge thanks for your work. Everything is better than I expected.

**Comment by BenoitDuffez** [comment]
That did fix another issue that I didn't understand, my prototype ends with an `<hr>` and I don't know why they were not placed where I wanted.
Now the `<hr>` are exactly where I want them to be.
Double fix! :)
