### ISSUE TITLE
The position is wrongly sorted when using a position field

### ISSUE THREAD

**Issue by leroy0211** [ninsuo/symfony-collection#70]
When you use a position field the position is wrongly sorted. 
In case you have less than 10 items in the list, everything goes well. But when you have more options, the sortation will be sorted on the string-representation of the position. 

In this case the sort of the positions 0 to 13 will be: 

```
 0, 1, 10, 11, 12, 13, 2, 3, 4, 5, 6, 7, 8, 9 
```

**Comment by ninsuo** [comment]
Hello,

Yes, not at submit, but at initialization it looks like there's a sorting issue.

Will look forward.

Thanks

**Comment by leroy0211** [comment]
I've got a fix for it. But it also includes a different approach for sorting the collection for the first time. 

I will make a pull-request for both of them (the fix and the different approach). So you can decide which to merge.

**Comment by ninsuo** [comment]
Fixed in #71
