### ISSUE TITLE
Broken order with nested collection

### ISSUE THREAD

**Issue by atallahade** [ninsuo/symfony-collection#73]
Using symfony collection 2.1.6, I have a nested collection like [this one](https://symfony-collection.fuz.org/symfony3/advanced/collectionOfCollections) and when I try to move a parent collection, then a child element, the name attribute of the child is not updated.

You can try this on the demo website (linked above):
1. Initialization: Element `a` name property = `form[collections][0][0][value]` (OK)
2. Move the first collection down: f`orm[collections][1][0][value]` (OK)
3. Move the `a` element down: `form[collections][1][0][value]` (NOT OK), should be `form[collections][1][1][value]`

As a result, when I save the form the order is not kept.

**Comment by ninsuo** [comment]
Thank you, I'll investigate this quickly.

A

**Comment by atallahade** [comment]
@ninsuo Thanks! :)

**Comment by ninsuo** [comment]
Hi @atallahade 

Thanks again for your bug report, it's a 2-years old bug but it seems that nobody used "move" on nested collections so far.

You can try the fix at https://symfony-collection.fuz.org/symfony3/advanced/collectionOfCollections

Enjoy

**Comment by atallahade** [comment]
Thank you @ninsuo for fixing the issue that quickly, that's great job!
