### ISSUE TITLE
Customize "collection-action collection-rescue-add" button style

### ISSUE THREAD

**Issue by picks44** [ninsuo/symfony-collection#80]
Do you provide an option for this?

**Comment by ninsuo** [comment]
Hello,

You can use `add` option to add styles on your `rescue-add` button.

```js
        $('.collection').collection({
            add: '<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span></a>'
        });
```

You can check the demo here: https://symfony-collection.fuz.org/symfony3/options/customButtons

If your add button layout is complex (generated with a form theme or such), you can set the `min` option to 1 to enforce your collection to have at least 1 element (so rescue-add will never appear).

**Comment by picks44** [comment]
@ninsuo nice thanks! It's working fine, even with a form theme.
