### ISSUE TITLE
How can I access a collection value in my form theme?

### ISSUE THREAD

**Issue by picks44** [ninsuo/symfony-collection#81]
I'm using this bundle, it's working perfectly to create my entities.

But then, if I want to access some values of my Collection data in my template that update the Entity (like an image to display it), I get this error : `Impossible to access an attribute ("imageName") on a null variable.`

I've managed to dump the form values like `{{ dump(form.vars.value) }}`  which returns me the entities of my Collection like this : 

```
ArticleAttachment {#3220 ▼
  -id: 6
  -imageFile: null
  -imageName: "59a68c78cca5c_2017-08-24 18.40.39-1.jpg"
  -imageUpdatedAt: DateTime {#5439 ▼
    +"date": "2017-08-30 09:59:20.000000"
    +"timezone_type": 3
    +"timezone": "UTC"
  }

```
 But then, if I want the imageName (or any other attribute), like `{{ dump(form.vars.value.imageName) }}`, I get the above error. The rest of the form is fine.

Any clue ?

Here is my form theme:

```
{% block attachment_label %}{% endblock %}

{% block attachment_widget %}
    <div class="row">
        <div class="col-md-4">
            {{ dump(form.vars.value.imageName) }}
        </div>
        <div class="col-md-2">
            {{ form_widget(form.imageFile) }}
            {{ form_widget(form.position) }}
            <p class="text-danger">{{ form_errors(form.imageFile) }}</p>
        </div>
        <div class="col-md-1">
            <a href="#" class="collection-up btn btn-default" title="Move fruit up"><span class="glyphicon glyphicon-arrow-up"></span></a>
            <a href="#" class="collection-down btn btn-default" title="Move fruit down"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
        <div class="col-md-1">
            <a href="#" class="collection-remove btn btn-default" title="Delete fruit"><span class="glyphicon glyphicon-trash"></span></a>
            <a href="#" class="collection-add btn btn-default" title="Add fruit"><span class="glyphicon glyphicon-plus-sign"></span></a>
        </div>
        <div class="col-md-1">
            <a href="#" class="collection-duplicate btn btn-default" title="Duplicate fruit"><span class="glyphicon glyphicon-th-large"></span></a>
        </div>
    </div>
{% endblock %}
```

**Comment by ninsuo** [comment]
Hi,

Can you try using:

```jinja
{{ dump(form.vars.value.get('imageName')) }}
```

**Comment by picks44** [comment]
Same error message `Impossible to invoke a method ("get") on a null variable.`

it's crazy because the var is NOT null haha.

**Comment by ninsuo** [comment]
Humm, like this I don't really know.

As your question isn't directly related to symfony-collection plugin, I advise you to open a question on Stackoverflow. The symfony community is far larger than here 😄

**Comment by picks44** [comment]
Alright!

**Comment by picks44** [comment]
Hi @ninsuo I'm still struggling with this I can't get any value of my collection in edit mode.
I'va raised an issue on [Stackoverflow also.](https://stackoverflow.com/questions/46031265/how-can-i-access-a-collectiontype-value-in-my-symfony-form-theme).

I'd be delighted to have some help here.

**Comment by ninsuo** [comment]
If you allow "add" images, I guess you enabled the collection prototype which helps generating new rows.

So you may try to use `{{ form.vars.value.imageName|default('<some default picture url>') }}` because your newly created elements do not contain any data yet.

**Comment by picks44** [comment]
I've updated my form theme like this, which is OK when you have one image. But if I edit my entity to add a second one, it make the first image as null.
I guess I have to go back to my old way of managing my collection then.

{% block image_widget %}
    <div class="row">
        <div class="col-md-4">
            {% if form.imageName.vars.value is empty %}
                No image yet!
            {% else %}
                {% set path = 'uploads/landingpages/' ~ form.imageName.vars.value %}
                <img class="img-thumbnail img-responsive" src="{{ asset(path|imagine_filter('thumb_lp')) }}">
            {%  endif %}
        </div>
        <div class="col-md-2">
            {{ form_widget(form.imageFile) }}
            {{ form_widget(form.position) }}
            <p class="help-block">700px wide min - jpg,png,gif - 1Mo max</p>
            <p class="text-danger">{{ form_errors(form.imageFile) }}</p>
        </div>
        <div class="col-md-1">
            <a href="#" class="collection-up btn btn-default" title="Move up"><span class="glyphicon glyphicon-arrow-up"></span></a>
            <a href="#" class="collection-down btn btn-default" title="Move down"><span class="glyphicon glyphicon-arrow-down"></span></a>
        </div>
        <div class="col-md-1">
            <a href="#" class="collection-remove btn btn-default" title="Delete"><span class="glyphicon glyphicon-trash"></span></a>
            <a href="#" class="collection-add btn btn-default" title="Add"><span class="glyphicon glyphicon-plus-sign"></span></a>
        </div>
        <div class="col-md-1">
            <a href="#" class="collection-duplicate btn btn-default" title="Duplicate"><span class="glyphicon glyphicon-th-large"></span></a>
        </div>
    </div>
{% endblock %}
