### ISSUE TITLE
Wrong index generation for nested collections

### ISSUE THREAD

**Issue by baltpeter** [ninsuo/symfony-collection#84]
Hi ninsuo,

first of all, thanks for the great plugin which is saving me a great deal of work! Unfortunately, I have an issue whereby it seems to be generating wrong indexes for nested collections. I have setup a demo repo which demonstrates this issue: https://github.com/baltpeter/symfony-collection-problem-demo

Basically, I have the following (simplified) data structure:

```php
HugoPost {#251 ▼
  +id: null
  +title: "demo"
  +recipe: HugoRecipe {#639 ▼
    +ingredients: array:2 [▼
      0 => IngredientCategory {#807 ▼
        +name: "IC 1"
        +contents: array:1 [▼
          0 => IngredientItem {#933 ▼
            +value: "value 1.1"
            +unit: null
            +name: null
            +note: null
          }
        ]
      }
      1 => IngredientCategory {#890 ▼
        +name: "IC 2"
        +contents: array:1 [▼
          1 => IngredientItem {#997 ▼
            +value: "value 2.1"
            +unit: null
            +name: null
            +note: null
          }
        ]
      }
    ]
    +steps: []
    +notes: null
  }
  +body: null
}
```

And I initialize the plugin like this:

```js
$('.ingredient-category').collection({
    drag_drop: false,
    prefix: "collection-ingredient-category",

    remove: '<a href="#">[ Delete ingredient category ]</a>',
    add: '<a href="#">[ Add ingredient category ]</a>',
    up: '<a href="#">[ &#x25B2; ]</a>',
    down: '<a href="#">[ &#x25BC; ]</a>',

    children: [
        {
            selector: ".ingredient-item",
            drag_drop: false,
            prefix: "collection-ingredient-item"
        }
    ]
});
```
Now, if I fill out the form like this:

![](https://i.imgur.com/APAbe4R.png)

Some items get overwritten and placed in the wrong category:

```php
HugoPost {#251 ▼
  +id: null
  +title: "demo"
  +recipe: HugoRecipe {#639 ▼
    +ingredients: array:2 [▼
      0 => IngredientCategory {#807 ▼
        +name: "IC 1"
        +contents: array:1 [▼
          0 => IngredientItem {#933 ▼
            +value: "value 2.1"
            +unit: null
            +name: null
            +note: null
          }
        ]
      }
      1 => IngredientCategory {#890 ▼
        +name: "IC 2"
        +contents: array:1 [▼
          1 => IngredientItem {#997 ▼
            +value: "value 2.2"
            +unit: null
            +name: null
            +note: null
          }
        ]
      }
    ]
    +steps: []
    +notes: null
  }
  +body: null
}
```

From what I can see, the issue seems to be with the index generation. When I add a second ingredient category and add an item to that, it gets a name attribute of `hugo_post[recipe][ingredients][0][contents][0][value]` where I would expect the correct value to be `hugo_post[recipe][ingredients][1][contents][0][value]`.

When I add additional items to the second category, it seems like the plugin is incrementing both indexes instead of only the second: The second item in the second category gets the name `hugo_post[recipe][ingredients][1][contents][1][value]`, the third `hugo_post[recipe][ingredients][2][contents][2][value]` and so on.

The same issue happens for the `steps` which have basically the same data structure.

Now, I hope this has not been reported before and that this is not some stupid error on my part but I appreciate your help with this. Thanks a lot in advance.

Cheers,
Benjamin

**Comment by ninsuo** [comment]
Hello Benjamin,

Thank you a lot for the effort you spent, I think you're my first contributor who clearly sweat opensouce.

I will care of your issue during the week-end.

A

**Comment by baltpeter** [comment]
Hi ninsuo,

thanks for your time! I did some more digging myself (i.e. I actually read your JS source; open source truly is great :)) and I'm pretty sure I found the issue: I didn't set unique `prototype_name`s for the parent and child in my Symfony post type. If I do that, your plugin works just fine and as expected.

So unfortunately, it seems like this was indeed a stupid error on my part. Apologies for that! And I feel even sillier considering you mention that in the README, I don't know how I overlooked that…

Unless you see anything else, we can close this issue.

Thanks again and have a nice weekend,
Benjamin

**Comment by ninsuo** [comment]
Ah damn, sorry about that!

Indeed on nested collections you need to provide a distinct `prototype_name` so generation can duplicate markup and `.replace` the right elements.

Don't hesitate if you have other troubles, and sorry for the delay.

**Comment by ljmoleiro** [comment]
Awesome library,
You should take in count @baltpeter suggestion, include in readme or in the example, the info to define the prototype_name in nested collections, it will save some time 😉
