### ISSUE TITLE
Getting TypeError: jQuery.ui is undefined after recent releases

### ISSUE THREAD

**Issue by sweoggy** [ninsuo/symfony-collection#92]
I am now getting jQuery.ui on my collections. Culprit seems to be this PR #90

**Comment by ninsuo** [comment]
Ah, sorry mate.
Will provide a fix asap.

**Comment by picks44** [comment]
Same issue here!
What is the version we need to revert to while you fix this? :)

**Comment by ninsuo** [comment]
I just fixed it, going to release a new version.
A

**Comment by ninsuo** [comment]
Done, you can upgrade to 2.1.18
Have a good day!

**Comment by picks44** [comment]
'm stuck with 2.1.17 :(

**Comment by picks44** [comment]
@ninsuo can you put 2.1.18 as stable release? I cannot upgrade to it as it is now.

**Comment by ninsuo** [comment]
Humm, it is a stable release :thinking: 
Which package manager are you using?

**Comment by picks44** [comment]
@ninsuo well when I do a `composer update`, it's stuck on 2.1.17. 

If I update my `composer.json` to  `"ninsuo/symfony-collection": "^2.1.18"`, I get this error

```
- The requested package ninsuo/symfony-collection ^2.1.18 exists as ninsuo/symfony-collection[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.1.0, 2.1.1, 2.1.10, 2.1.11, 2
.1.12, 2.1.13, 2.1.14, 2.1.15, 2.1.16, 2.1.17, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, dev-master] but these are rejected by your constraint.
```

**Comment by ninsuo** [comment]
I am sorry but I don't understand...

```sh
alain@iMac /tmp/test 
$ composer require ninsuo/symfony-collection
Using version ^2.1 for ninsuo/symfony-collection
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing ninsuo/symfony-collection (2.1.18): Downloading (100%)         
Writing lock file
Generating autoload files
alain@iMac /tmp/test 
```

Can you try to remove your cache (empty directory returned by `composer config cache-dir`)?

**Comment by picks44** [comment]
Now it's OK... very strange, it's the first time I have to do this in years haha

**Comment by sweoggy** [comment]
Thanks a lot @ninsuo works great!

**Comment by picks44** [comment]
Yep, thanks :)
