### ISSUE TITLE
Regenerated prototype is not taken in account when create a new dynamic field.

### ISSUE THREAD

**Issue by Axxon** [ninsuo/symfony-collection#94]
Hello, i have a special case when i need to regenerate the prototype so the new element are changed. A list is created base on a prototype (but i want some items disapear after some user interactions). In back i regenerate the prototype and  replacewith the original. But it does not work. Do is there a way to the plugin recalculate what is prototype ?

**Comment by ninsuo** [comment]
Hello @Axxon ,

Currently, prototype is taken by using `collection.data('prototype')`, so to enforce refreshing it, you may try to do something like `$(collection).data('prototype', $(collection).attr('data-prototype'));`.

I don't really know though, it may depend on your context. How do you regenerate the prototype and where do you store it?

A

**Comment by Axxon** [comment]
Thanks à lot for your quick return. I fixes my issue with .data() i did not understood why the dom was not updated when i call data instead of attr, but this is normal.

**Comment by ninsuo** [comment]
Ah yeah, calling `.data` from jquery is in memory only, where calling `.attr('data', ...)` writes the dom. Everybody do the mistake once don't worry 👍
