### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by DBarkz** [ninsuo/symfony-collection#95]
Hi there

I just came across this bundle and successfully installed and began to follow your documentation how how to set it up, I got to the end of the 'A simple collection' of you documentation, and I now have the + and - on my form. When I click the + or try to move items up and down it works fine but when I click the - and then try to add another item I get the following error:

```
Uncaught TypeError: Cannot read property 'attributes' of undefined
    at replaceAttrDataNode (jquery.collection.js:182)
    at replaceAttrData (jquery.collection.js:195)
    at changeElementIndex (jquery.collection.js:219)
    at swapElements (jquery.collection.js:259)
    at doMove (jquery.collection.js:635)
    at doAdd (jquery.collection.js:537)
    at HTMLAnchorElement.<anonymous> (jquery.collection.js:861)
    at HTMLBodyElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLBodyElement.q.handle (jquery-3.2.1.min.js:3)
```

Is this something that's been encountered before, and how do I resolve it?

Thanks

**Comment by ricky6982** [comment]
Hi DBarkz, I have the same issue...

**Comment by ninsuo** [comment]
Hello there,

Which browser are you using?

Indeed there is no check at line 181, but Chrome & Firefox don't seem to care. I may be missing some strict utility or something like that.

A

**Comment by DBarkz** [comment]
Hi, thanks for your reply,

I am using Chromium 62.0.3202.62

**Comment by ninsuo** [comment]
Cool! I can reproduce it using Chromium.
Good to know that Chromium is stricter than other "common" browsers.
Will test the whole plugin today to fix those exceptions.

**Comment by DBarkz** [comment]
Awesome, thanks for your help!

**Comment by DBarkz** [comment]
Just fyi, I also just tested this in firefox and I was also having the same issue on there.

**Comment by ninsuo** [comment]
I fixed a bunch of issues related to this. Chromium has good stack traces by the way.

I noticed other issues when fade_in / fade_out / move_down are enabled (like removing an element at the bottom when you have >=4 elements adds an unexpected move_down arrow). Will check that later on.

Have a good Sunday.

**Comment by DBarkz** [comment]
Thanks for this, is now working perfectly, and it is awesome! Great communication and bundle :)
