### ISSUE TITLE
collection embedded in another collection

### ISSUE THREAD

**Issue by ricky6982** [ninsuo/symfony-collection#97]
Hi there! I wanna know if there is the possibility of have a first collection and another collection inside her.

**Comment by ninsuo** [comment]
You mena nested collections?
Please have a look here: http://127.0.0.1:8000/advanced/collectionOfCollections

**Comment by ninsuo** [comment]
Arh, I mean, here: https://symfony-collection.fuz.org/symfony3/advanced/collectionOfCollections

**Comment by ricky6982** [comment]
Yes! Thank you!
