### ISSUE TITLE
nested collection 

### ISSUE THREAD

**Issue by Punt13140** [ninsuo/symfony-collection#98]
Hi,

First, thanks for your work, it helped me a lot to customize my collections.
I'm having some trouble with nested collection.
I have an entity Application, which has a collection of LienAppliServ :
```php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('servLiens', 'collection', array(
                'label' => 'Lien appli-serveur',
                'type' => new LienAppliServType(),
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' =>false,
                'prototype' => true,
                'attr' => array('class' => 'collection-liens'),
                'prototype_name' => '__parent_name__'
            ))
```

In LienAppliServ, I also have a collection of Ports : 

```php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
            ->add('ports', 'collection', array(
                'type' => new PortLienAppliServType(),
                'allow_add' => true,
                'allow_delete' => true,
                'prototype' => true,
                'by_reference' =>false,
                'attr' => array('class' => 'collection-ports'),
                'prototype_name' => '__children_name__'
            ))
```

But, when I call the js on the selector, there is a problem.

If I do : 
```javascript

        $('.collection-liens').collection({
            add: '<br><a class="btn btn-success" href="#"><span class="glyphicon glyphicon-plus"></span> Ajouter une association avec un serveur</a>',
            remove: '<a class="btn btn-danger" href="#"><span class="glyphicon glyphicon-remove"></span></a>',
            allow_up: false,
            allow_down: false,
            allow_duplicate: false,
            add_at_the_end: true,
            prefix: 'parent'

```

I understand why the port's collection isn't handled.
But when I do : 
```javascript
        $('.collection-liens').collection({
            add: '<br><a class="btn btn-success" href="#"><span class="glyphicon glyphicon-plus"></span> Ajouter une association avec un serveur</a>',
            remove: '<a class="btn btn-danger" href="#"><span class="glyphicon glyphicon-remove"></span></a>',
            allow_up: false,
            allow_down: false,
            allow_duplicate: false,
            add_at_the_end: true,
            prefix: 'parent',
            children: [{
                prefix: 'child',
                selector: 'collection-ports',
                add: '<br><a class="btn btn-success" href="#"><span class="glyphicon glyphicon-plus"></span> Ajouter un port</a>',
                remove: '<a class="btn btn-danger" href="#"><span class="glyphicon glyphicon-remove"></span> -</a>',
                allow_up: false,
                allow_down: false,
                allow_duplicate: false,
                add_at_the_end: true
            }]
```

There is a log : jquery.collection.js: given collection selector does not exist.

Maybe I missed something ?
(btw It's Symfony 2.7)

**Comment by ninsuo** [comment]
Hey there!

I think you forgot a dot in your children selector, try to replace:

```js
                selector: 'collection-ports',
```

by:

```js
                selector: '.collection-ports',
```

Cheers

**Comment by Punt13140** [comment]
I guess I was tired.. Well, it's sort of working...
I have my child collection-ports, but if I remove a parent collection, the next collection will have some problems... 

![capture du 2017-11-07 09-58-18](https://user-images.githubusercontent.com/33422215/32485262-0a65e2c6-c3a3-11e7-947b-745b42a81c8a.png)

Like you can see in 1 and 2, there is some trouble for the child collection... 
Sometimes there is no 'add button' and sometimes there is 3 'add button' for the child collection...

Any idea ?

**Comment by ninsuo** [comment]
Hey there,

I believe your children add buttons haven't the right classes.

As you prefixed `child` on your nested collection, your button should be something like:

```html
<a class="child-add child-action" ... >Ajouter un port</a>
```

Have a good day!
Alain

**Comment by Punt13140** [comment]
Still having this issue...
So here are my forms theme : 

Parent form : 
```html
{% block lienAppliServType_row %}
    <br>
    <div class="row ">
        <div class="col-md-2">

            <div class="text-center">{{ form_label(form.typeServeur) }}</div>
            <div>{{ form_widget(form.typeServeur) }}</div>
        </div>
        <div class="col-md-4">
            <div class="text-center">{{ form_label(form.serv) }}</div>
            <div>{{ form_widget(form.serv) }}</div>
        </div>
        <div class="col-md-4">
            <div>{{ form_widget(form.ports) }}</div>
        </div>
        <div class="col-md-1">
            <br style="margin-top: 6px">
            <a href="#" class="parent-remove btn btn-danger" title="Supprimer la documentation"><span class="glyphicon glyphicon-trash"></span></a>
        </div>
    </div>
{% endblock %}
```


Child form : 
```html
{% block portType_row %}
    <br>
    <div class="row" style="border: solid 1px; padding: 10px; border-color: #ddd;">
        <div class="col-md-6">
            <div class="text-center">{{ form_label(form.numPort) }}</div>
            <div>{{ form_widget(form.numPort) }}</div>
        </div>
        <div class="col-md-4">
            <div class="text-center">{{ form_label(form.type) }}</div>
            <div>{{ form_widget(form.type) }}</div>
        </div>
        <div class="col-md-2">
            <br style="margin-top: 7px">
            <a href="#" class="child-remove btn btn-danger" title="Supprimer le port"><span class="glyphicon glyphicon-trash"></span></a>
        </div>
    </div>
{% endblock %}
```

JS : 
```javascript
        $('.collection-liens').collection({
            prefix: 'parent',
            add: '<br><a class="btn btn-success" href="#"><span class="parent-add glyphicon glyphicon-plus"></span> Ajouter une association avec un serveur</a>',
            remove: '<a class="btn btn-danger" href="#"><span class="parent-remove glyphicon glyphicon-remove"></span></a>',
            allow_up: false,
            allow_down: false,
            allow_duplicate: false,
            add_at_the_end: true,
            children: [{
                prefix: 'child',
                selector: '.collection-ports',
                add: '<br><a class="btn btn-success" href="#"><span class="child-add glyphicon glyphicon-plus"></span> Ajouter un port</a>',
                remove: '<a class="btn btn-danger" href="#"><span class="child-remove glyphicon glyphicon-trash"></span></a>',
                allow_up: false,
                allow_down: false,
                allow_duplicate: false,
                add_at_the_end: true
            }]
```

Only when I delete a parent row...

**Comment by Punt13140** [comment]
Whoups.. Didn't want to close... sorry.

UP ^^

**Comment by ninsuo** [comment]
I am currently busy and will go on weekend afterwards so please do not expect a quick answer from me

Sorry 😓

Have a good day

**Comment by Punt13140** [comment]
Sure, take your time, I'm working on something else actually and i'll try to correct this later :)

**Comment by Punt13140** [comment]
UP ! I wanna release my 1.0 this week and I think it's the only issue left... ^^

**Comment by ninsuo** [comment]
Hi,

First, to trigger the delete button the right way, instead of 

```js
          add: '<br><a class="btn btn-success" href="#"><span class="child-add glyphicon glyphicon-plus"></span> Ajouter un port</a>',
         remove: '<a class="btn btn-danger" href="#"><span class="child-remove glyphicon glyphicon-trash"></span></a>',
 ```

I'd put:

```js
          add: '<br><a class="btn btn-success child-add" href="#"><span class="glyphicon glyphicon-plus"></span> Ajouter un port</a>',
         remove: '<a class="btn btn-danger child-remove" href="#"><span class="glyphicon glyphicon-trash"></span></a>',
 ```

Next, for the issue you have, just like you did in your form theme:

```jinja
            <a href="#" class="child-remove btn btn-danger" title="Supprimer le port"><span class="glyphicon glyphicon-trash"></span></a>
```

I'd put the "ajouter un port" button in the form-theme so the collection plugin won't generate it with its own markup.

Finally, I don't know if it could change something, but the `lienAppliServType_row` collection has 11 columns instead of 12.

This is hard to help further without any code that I can run and debug...

**Comment by Punt13140** [comment]
I sent you an email with the jsfiddle (I'd like to not share it here thanks.)

I changed the delete button as you said !
And changed the number of columns too...

But I didn't succeed to put the button in the form-theme.. How would you do that ?
Thanks for your time !

**Comment by ninsuo** [comment]
I wasn't able to reproduce your issue in the fiddle, 
- can you give me the "steps" (like "add a child here", "add a parent there", "remove the first child collection" etc?
- remove the `<br/>` above your `<div class="row">` in the form themes as it does not take part of your child elements (see your option `elements_selector: '> div'`

**Comment by ninsuo** [comment]
Ok will look from home, i indeed can reproduce the issue but will put all this in a clear .html page for easier debugging.

**Comment by Punt13140** [comment]
Ok, I'll send you another email so that you can reproduce it easier ;)

**Comment by ninsuo** [comment]
Ok thank you for your perseverance and I'm really sorry for the delay.

Indeed, there is an issue with the "rescue add" button which is used both when there are no more elements in the collection or when add_at_the_end option is set to true.

Selector of that button is the following: `$('.' + settings.prefix + '-rescue-add')`, which has no sense on nested collections that has many child sharing the same prefix.

I'm currently developing the fix.

Again, thanks a lot for your perseverance.

**Comment by ninsuo** [comment]
Hello @Punt13140 ,

I successfully found a solution.
https://github.com/ninsuo/symfony-collection/pull/107

Please test and let me know if everything is fine.
If any issue, please reopen this one 👍

**Comment by Punt13140** [comment]
Hello @ninsuo,
Everything is fine.
Once again, Thanks for your work !
