### ISSUE TITLE
Double indexes

### ISSUE THREAD

**Issue by kprimc** [ninsuo/symfony-collection#99]
Hello,

first of all... good job!

I notices a bug. If you go to your demo page:
https://symfony-collection.fuz.org/symfony3/

Inspect 'Orange' input, you will see it has ID 'withPlugin_fruits_2_name'

Now, do the following:
- add fruit (from 'Orange' line input)
- remove newly added fruit
- add fruit (from 'Orange' line input)
- add fruit (from newly created fruit line)

You will notice, the last two of them have ID 'withPlugin_fruits_4_name'. If you add another fruit, the next one will have ID 'withPlugin_fruits_5_name', which is OK.

Any help around this? In my example, I have tinyMCE to initialize, but it does not because of two identical ID's of textarea.

Edit:
The same problem is with nested children:
https://symfony-collection.fuz.org/symfony3/advanced/collectionOfCollections

**Comment by ninsuo** [comment]
Hey there!

Thank you, I'm not available until tomorrow night but I'll have a look soon enough.

Have a good day,
Alain

**Comment by ninsuo** [comment]
Hey there,

Yeah that's easy to reproduce, thanks for your report.

You can get rid of this issue by disabling fade_in and fade_out options.

Alain

**Comment by ninsuo** [comment]
fade_in and fade_out are a nightmare with many edge cases, it will be IMO more productive to remove them.

**Comment by kprimc** [comment]
Hey,

thanks for the quick reply!
Do you perhaps know when you will have time to fix it?

**Comment by ninsuo** [comment]
Well, I'll be quite busy this week (even the weekend), but everything should go smoother after.

Just disable `fade_in` and `fade_out` options (they are enabled by default) and you'll be good to go.

Cheers

**Comment by kprimc** [comment]
Hello,

I just tried to disable `fade_in` and `fade_out`, but that didn't resolved the issue. I disabled it at parent level, and also at child level.

The animation went away, but there is still problem with double indexes.

**Comment by ninsuo** [comment]
Okey. Will try to find some time to check/fix it quickly.

**Comment by ninsuo** [comment]
later is better than never... on it now 😅

**Comment by ninsuo** [comment]
all right, found it, the `last-index` was wrongly initialized, fix onging

**Comment by kprimc** [comment]
Thank you, it works :)
